# Scheduled refresh of the generated merchant table.
#
# Runs the full chain and stops at the first thing that fails:
#
#   generate  -> scripts/merchant-table.candidate.json   (a proposal, nothing shipped)
#   validate  -> merchant-table.js                       (only if the gate passes)
#   test      -> the whole suite, not just the table tests
#   PR        -> a branch + pull request for review
#
# It never commits to master and never force-pushes. A language model writing
# unattended into a shipped artifact is fine exactly as long as a human sees the
# diff before users do -- cron proposes, you dispose.
#
# WHY THIS IS NOT A GITHUB ACTION
# ------------------------------
# The generator authenticates as the local Claude Code subscription. Those
# credentials live on this machine and do not travel to CI, which is the whole
# reason this costs nothing per run. Running it in Actions would require an
# ANTHROPIC_API_KEY and a per-run bill. So it is scheduled locally instead:
#
#   schtasks /create /tn "Sula merchant table" /sc WEEKLY /d SUN /st 03:00 ^
#     /tr "powershell -NoProfile -ExecutionPolicy Bypass -File C:\Users\User\find-me-people\scripts\refresh-merchant-table.ps1"
#
# Usage:  powershell -File scripts/refresh-merchant-table.ps1 [-NoPr]

param([switch]$NoPr)

$ErrorActionPreference = "Stop"
Set-Location (Join-Path $PSScriptRoot "..")

function Step($msg) { Write-Host "==> $msg" -ForegroundColor Cyan }

# Refuse to run on a dirty tree. Otherwise the PR quietly carries whatever
# unrelated work happened to be sitting in the working copy.
$dirty = git status --porcelain
if ($dirty) {
  Write-Error "Working tree is dirty. Commit or stash first:`n$dirty"
  exit 1
}

Step "Generating candidate"
node scripts/generate-merchant-table.mjs
if ($LASTEXITCODE -ne 0) { Write-Error "Generation failed; nothing changed."; exit 1 }

Step "Validating and promoting"
node scripts/validate-merchant-table.mjs --promote
if ($LASTEXITCODE -ne 0) { Write-Error "Candidate rejected; merchant-table.js untouched."; exit 1 }

Step "Running the test suite"
npm test
if ($LASTEXITCODE -ne 0) {
  Write-Error "Tests failed. Reverting merchant-table.js."
  git checkout -- merchant-table.js
  exit 1
}

$changed = git status --porcelain merchant-table.js
if (-not $changed) {
  Step "Table is unchanged since the last run. Nothing to propose."
  exit 0
}

$added = (git diff --numstat merchant-table.js | ForEach-Object { ($_ -split "`t")[0] })
$removed = (git diff --numstat merchant-table.js | ForEach-Object { ($_ -split "`t")[1] })
Step "Table changed (+$added / -$removed lines)"

if ($NoPr) {
  Step "-NoPr set. Leaving the change in the working tree for review."
  exit 0
}

$branch = "chore/merchant-table-" + (Get-Date -Format "yyyy-MM-dd")
Step "Opening PR on $branch"

git checkout -b $branch
git add merchant-table.js
git commit -m @'
Refresh the generated merchant table

Regenerated by scripts/refresh-merchant-table.ps1 on a schedule. The candidate
cleared scripts/validate-merchant-table.mjs -- schema, coherence, coverage, and
the pinned golden cases in scripts/merchant-golden.json run through the real
normalizeMerchant -- and the full test suite passed.

Static data only. The extension still makes no network call and no model call,
and a statement is still parsed entirely in the browser.

Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>
'@

git push -u origin $branch

gh pr create --fill --body @'
Scheduled regeneration of `merchant-table.js`.

Generated by `scripts/generate-merchant-table.mjs` (Claude Code headless, local
subscription auth -- no API key, no per-run cost) and promoted only after
clearing `scripts/validate-merchant-table.mjs`.

**Review the diff, not the process.** The gate proves the pinned descriptors in
`scripts/merchant-golden.json` still resolve correctly and that no previously
shipped merchant was dropped. It cannot prove a newly added merchant is real --
skim the added entries for anything invented.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
'@

Step "Done."
